notifications:
  email:
  - cf-lamb@pivotallabs.com

language: go

go:
- 1.4
- tip

matrix:
  allow_failures:
  - go: tip

before_install:
- go get golang.org/x/tools/cmd/cover golang.org/x/tools/cmd/vet
- go get -v github.com/mattn/goveralls
- go get -v github.com/onsi/ginkgo
- go get -v github.com/onsi/gomega
- go get -v github.com/golang/lint/golint
- go install -v github.com/onsi/ginkgo/ginkgo

install:
- go get -v -d -t ./...

script: PATH=$HOME/gopath/bin:$PATH bin/test

after_success:
- 'echo "mode: set" > all.coverprofile'
- 'find . -name "*.coverprofile" -exec grep -v mode: {} >> all.coverprofile \;'
- "$HOME/gopath/bin/goveralls -coverprofile=all.coverprofile -repotoken=$COVERALLS_TOKEN"

COVERALLS_TOKEN:
  secure: AX2lu4hfmZHwcKI6E7RIoBcAw8KanvVKpNvCE5AuYdnT4bhmZJGsNnLPufYEFe+t6aB530QTdvuJHIxOexhlOZ2BQVHa3Ljc9HWxZX9+h7NYEPLbx/7wcELedko2VuL6Yr0qfDmLCx3YbyRw5Q8oc7/IGrWiHdBdK2Udf+vNKlE=
